server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CITIZEN-SERVICE
          uri: lb://CITIZEN-SERVICE
          predicates:
            - Path=/citizen/**
        - id: VACCINATION-CENTER-SERVICE
          uri: lb://VACCINATION-CENTER-SERVICE
          predicates:
            - Path=/vaccination/center/**
