server:
  port: 8082

spring:
  application:
    name: VACCINATION-CENTER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YOGkp8808@
    url: jdbc:mysql://localhost:3306/vaccination_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

